#!/usr/bin/env zsh

# exit early if config doesn't exist
if [[ ! -r "${0:h}/config" ]]; then
  print "${0:h}/config does not exist. Cannot execute githooks"
  exit 1
fi

# read the config
source ${0:h}/config

# execute each hook
for hook in ${_hooks_commit_msg}; do
  ${hook} ${1}
done
