#!/usr/bin/env zsh

# a tty must be allocated to read stdin, necessary
# for hooks like interactive-secrets
exec < /dev/tty

# exit early if config doesn't exist
if [[ ! -r "${0:h}/config" ]]; then
  print "${0:h}/config does not exist. Cannot execute githooks"
  exit 1
fi

# read the config
source ${0:h}/config

# execute each hook
for hook in ${_hooks_pre_commit}; do
  ${hook}
done
