#!/usr/bin/env zsh

# exit early if config doesn't exist
if [[ ! -r "${0:h}/config" ]]; then
  print "${0:h}/config does not exist. Cannot execute githooks"
  exit 1
fi

# read the config
source ${0:h}/config

# a tty must be allocated to read stdin, necessary
# for hooks like interactive-secrets
exec < /dev/tty

# for each hook, add the result as a note, with the hook name as the ref
for hook in ${_hooks_pre_push}; do
  out=$(${hook} 2>&1)
  #exitCode=${?}
  if [[ ${out} != "" ]]; then
    echo ${out}
    git notes --ref="${hook}" add -f -m "${out}"
  fi
done

## and after we're done evaluating all of the hooks, create a summary to be attached to the main ref
#for hook in "${hooks}"; do
#  note="$(git notes --ref=${hook} show)"
#done

exit 1
